services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: ./.docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: paris
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: paris
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
